name: Rev. Cheryl
favicon: null
layout_spectrum: 0.7437029832508415
typography_spectrum: 0.8543679274152964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8336913886014372
  lightness: 0.05822638235986233
  saturation: 0.9454649509862065
  rhythmicContrast: 0.22095991903916
purpose: []
